services:
  - type: web
    name: portfolio
    env: node
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    plan: free
    branch: main
